//Check If The Number Is Positive Or Negative Number
#include<iostream>
using namespace std;
int main(){
/*int numBer ;
cout<<" Enter the number : ";
cin>> numBer;
if( numBer > 0){
    cout<<" The Number is Positive "<<endl;
}else if( numBer < 0){
    cout<<" The Number is Negative "<<endl;
}else{
    cout<<" The Number is Zero "<<endl;
} return 0;
*/


//switch

int num = 2;
switch(num){

case 1:
    cout<<"the value is 1";

case 2:
    cout<<"the values is 2";
case 3:
    cout<<"the value is 3;
default:
    cout<<"xxxxxxxxxxxxxxxxxxx";


}
}

