         //C INPUT
#include<iostream>
using namespace std;
int main(){

    string dob;
    cout<<"enter your dob";

    month = stoi(dob.substr(0, 2));
day = stoi(dob.substr(3,5));
year = stoi(dob.substr(6,10));

string name;
cout<<"Enter Your Name"<<endl;
cin>>name;
cout<<"Your Name is "<<name<<endl;
double age;
cout<<"Enter Your Age"<<endl;
cin>>age;
cout<<"Your Age is "<<age<<endl;
string address;
cout<<"Enter Your Address"<<endl;
cin>>address;
cout<< "Your Address is "<<address<<endl;
string fathername;
cout<<"Enter Your Father Name"<<endl;
cin>> fathername;
cout<<"Your Father Name is "<<father name<<endl;
string mothername;
cout<<"Enter Your Mother Name"<<endl;
cin>>motherName;
cout<<"Your Mother Name is "<<mother name<<endl
return 0;}
